#!/usr/bin/env bash
# Install Nginx on the server

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service ngix start
