#!/usr/bin/env bash
# Instal and configure Nginx so its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" |sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
sed -i "s/server_name_;/&\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default
# Redirect for 404 error page
sed -i "s/server_name_;/server_name_;\n\trewrite ^\/redirect_me hhtps:\/\/github.com\/Mukeli3 permanent;\n\n\terror_page 404 \/404.html;\n\location \/404 {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx restart
