#!/usr/bin/env bash
# script generates a MySQL dump and creates a compressed archive out of it

mysqldump --user=root --password="$1" --all-database > backup.sql
date=$(date +'%d-%m-%Y')
tar -czvf "${date}.tar.gz" backup.sql
