#!/usr/bin/env bash
# Script displays a list of currently running processes
# Requirements: must show all processes, for all users, including those which might not have a TTY,
# display in a user-oriented format and show processes hierarchy

ps auxf
