#!/usr/bin/env bash
# script creates the file /var/run/myscript.pid containing its PID,
# displays To infinity and beyond indefinitely,
# displays I hate the kill command when receiving a SIGTERM signal,
# displays Y U no love me?! when receiving a SIGINT signal and
# deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap 'handle' QUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
