#!/usr/bin/env bash
#script displays : To infinity and beyond indefinitely, with a sleep 2 in between each iteration, I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' TERM

while :
do
	echo "To infinity and beyond"
	sleep 2
done
