#!/usr/bin/env bash
# configure an ubuntu server with: localhost resoloves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts 
